const ACTIONS = {
    GET_PRODUCTS_OVERVIEW: "GET_PRODUCTS_OVERVIEW",
    GET_PRODUCTS_OF_CATEGORY: "GET_PRODUCTS_OF_CATEGORY",

    TOGGLE_MENU: "TOGGLE_MENU",

    INCREMENT_COUNTER: "INCREMENT_COUNTER",
    DECREMENT_COUNTER: "DECREMENT_COUNTER",

    ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",

    SHOW_NOTIFICATION: "SHOW_NOTIFICATION",
    HIDE_NOTIFICATION: "HIDE_NOTIFICATION",

    SHOW_DROPDOWN: "SHOW_DROPDOWN",
    HIDE_DROPDOWN: "HIDE_DROPDOWN",

}

export default ACTIONS
